language: node_js
node_js:
- node
deploy:
  api_key:
    secure: KYO6aWqk2+pjyFJl9h0Vff8H0m17wObfrUXz79JdIIqfVy/RHIcQffcuj+qkSlf8OBf/KtvagrudCSlmBKVBmliX1CgRYWXYdQ44Q4vmMjmRFcLCUUZQ4sB/SDSTQnf+MU6dkwakSs6oV3lQ91Y94Z+qQyn7PpsOGluANmU3O/7srqGqu2JLmpXJAc4NfcXFKXBcKVNcFXJUCq3BqSD0QnWgqZYTwgGM50yvV908Gtt9nCKAKgxvrrP9NAl73BNZ0BlkdnE4HtFT6YYOWi+YOzCj4dtDFCwqfA3sgVvB9Io4KJGxFp1OH+mrIYMVZhsrr7UROnnzEVYWE/sE2xTGJT7tGtY/d3AJZhtaawdaMY+Ec/x/y0oLIYeJ7wqon2HZqqrXsd59ndUhsbMV075AvZ7Yt+Qjwag4SGrjGxk/AvNQhQPJizc3Wz2KRlQlb1Pxz7rBN0YPiP8IzR79Yjn039A4853SOj4uhrFGzUfRdVHK1+1E2f/+ywwC+1NJk7fXDJvGmq/lyogm9l69NYBI5/3A4pIZZzVZNd9hDEXlUFMqV5g3V0iUjgNc4emXoUV9IYTnQX0iKuN8XupaC3m4O5ZwRfKTqNo+jPU3yVdBfXnkZ6K8QT0VWhPGbHBInO/PJ8Rjpm0rxC2dEydFLdQZKZomrXUl9jugRyMLsdarjwI=
