language: node_js
node_js:
- node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: ZJUHH1DNtREy46MdgctOMo0eX626amiIT7/jxgwojb/iOY75AhXDAJAPDVaV7I8uClde7TGLTCEwz85AAJCHYcAMY0Q3cxLoaqjvT+ASGt511FTlXsoEs5qQ/3f5uMSvzA1CbGP39LiU6LozUY7LaZTpkqCyf8JGsmyWXbPDcIsWSSsiiaRKEP0tM8p9gXwBbdpMPyZF73KzHeVbHGhNbDMHDfxc84uO+qLLu43TowuoVTCZUGrYXKCY2+nZhkqxE9NbOKsOnXsfC7xGx7/ADMNMOxVaG7C5tF5J53OmOmXuJEBLDowrI+gw33UYByxezZFq1MI8d74Tc4Rf/MFaDoQyczd4WJHrX3e0LUakf6udneXWiKJ/IHRITT9KHzDvMeJtkFctGtWyiHrRqHDT3T5egS5+gubPM61g3XEdp84Gcwxq30LvsP3sRF6Jg5TaCsPcpfEwKtxn/SWMltREbllytmQwQRMUmAs6cMYk6iP0tYuaPO78QhxPYmTm0DyxIugy20mz/wwjd1pHrGXunlYCrRKHsA74juWXNRf45Vpi5+eaewVB1fUXqtoX2FjgIVGtPpK+7wQ3EYKr1h2yUzspu5lMsRd1KwBw1ctVDQxsVsuwluOoo5xGNpFJsiH3nA/vWPeybezEnuKLupHbE9FlY9b4iZZlOrxE1ipPeZ8=
  app: band-up-server
  on:
    repo: BandUp/band-up-server
