language: node_js
node_js:
- node
deploy:
  api_key:
    secure: jxmpFWwJylr7sDJ1MN2qd2YODwnRXRm829f65SgcpL6aHbzz/LynTkyEaQiF4Cfg4/bHDT1yq+VTIPM6xAgukjwhjTx8zjvBWmeb9mOTMogGJ5ZeuztzucKJvUwUJ6XKJM/Suk7SOznetppoipEVqiDfNSuTVowOYli8/03zbhk0VRowQk/SFurRIwVnO2cjCJreU24cQIzJ2uIbFwC7eHyEoqzBcNKieAJCk0zsgw/L2uPS/cNJ3xV6OLaH7HE1OY2055lqn0rABOfHlnNNYnR8PZjis4GJy1Mwyw4r0ebMrBfG2KTo8QrfmFpEfPIN5v9WtvPzhWm0uGXfTWV4Z5+GcjF/O4/u44d9N5Tkvsg2qAg8dHfduWBe0DCFk0Bc2CndoZ8jmVNwM1S1AiKB2noHsyzwFgR4cst5YFRcggvbRonwzkLsyaCzEcuTU3AflpEkSMEEb5bM8jOju1vvCMq1TYwp1q2GtEqK6naeTKV/LpNTIh1SeMwfduoroWNO/mKidGafLWEHrT/FDcJ/0R0zKHzgPD6PTzWJy2pV0t20R1E46SlJfnNnSfAJqgrzMRWbJQOck/QW8fFsLNX9LXzzoh3QCpy8eLJgfcDb7Erzyv1NoKT1pDE/TEevlYevoc36DtnOi2IyCxahIoRjwuzAXG5/nJXg68l+8pBBcZQ=
